-- INSERT INTO burgers (burger_name) VALUES ('The AvoCali');
-- INSERT INTO burgers (burger_name) VALUES ('The OMG');
-- INSERT INTO burgers (burger_name) VALUES ('The Basic Bro');
-- INSERT INTO burgers (burger_name) VALUES ('The Pretensh');
-- INSERT INTO burgers (burger_name) VALUES ('The Obvi');
-- INSERT INTO burgers (burger_name) VALUES ('The Man-Bun');
